package com.uc.caffeine.ui.theme

import androidx.compose.ui.graphics.Color

val EspressoPrimaryLight = Color(0xFF6B4B2B)
val OnEspressoPrimaryLight = Color(0xFFFFFFFF)
val EspressoPrimaryContainerLight = Color(0xFFF7DFC3)
val OnEspressoPrimaryContainerLight = Color(0xFF251406)

val EspressoSecondaryLight = Color(0xFF695847)
val OnEspressoSecondaryLight = Color(0xFFFFFFFF)
val EspressoSecondaryContainerLight = Color(0xFFF0E0CC)
val OnEspressoSecondaryContainerLight = Color(0xFF24190F)

val EspressoTertiaryLight = Color(0xFF50653F)
val OnEspressoTertiaryLight = Color(0xFFFFFFFF)
val EspressoTertiaryContainerLight = Color(0xFFD4EABC)
val OnEspressoTertiaryContainerLight = Color(0xFF122004)

val CaffeineBackgroundLight = Color(0xFFFFF8F4)
val OnCaffeineBackgroundLight = Color(0xFF201A17)
val CaffeineSurfaceLight = Color(0xFFFFF8F4)
val OnCaffeineSurfaceLight = Color(0xFF201A17)
val CaffeineSurfaceVariantLight = Color(0xFFE7DED6)
val OnCaffeineSurfaceVariantLight = Color(0xFF50453D)
val CaffeineOutlineLight = Color(0xFF84746A)
val CaffeineOutlineVariantLight = Color(0xFFD1C5BB)
val CaffeineSurfaceDimLight = Color(0xFFE8D8CF)
val CaffeineSurfaceBrightLight = Color(0xFFFFF8F4)
val CaffeineSurfaceLowestLight = Color(0xFFFFFFFF)
val CaffeineSurfaceLowLight = Color(0xFFFBF1EA)
val CaffeineSurfaceContainerLight = Color(0xFFF6EAE2)
val CaffeineSurfaceHighLight = Color(0xFFF0E1D8)
val CaffeineSurfaceHighestLight = Color(0xFFE8D7CD)
val CaffeineInverseSurfaceLight = Color(0xFF352F2B)
val CaffeineInverseOnSurfaceLight = Color(0xFFFBEFE8)
val CaffeineInversePrimaryLight = Color(0xFFDDB892)

val EspressoPrimaryDark = Color(0xFFDDB892)
val OnEspressoPrimaryDark = Color(0xFF3B2611)
val EspressoPrimaryContainerDark = Color(0xFF56391E)
val OnEspressoPrimaryContainerDark = Color(0xFFF8DFC4)

val EspressoSecondaryDark = Color(0xFFD4C0AC)
val OnEspressoSecondaryDark = Color(0xFF382B1E)
val EspressoSecondaryContainerDark = Color(0xFF4F3F31)
val OnEspressoSecondaryContainerDark = Color(0xFFF1DECA)

val EspressoTertiaryDark = Color(0xFFB8D09E)
val OnEspressoTertiaryDark = Color(0xFF243515)
val EspressoTertiaryContainerDark = Color(0xFF394D28)
val OnEspressoTertiaryContainerDark = Color(0xFFD4EABC)

val CaffeineBackgroundDark = Color(0xFF17120F)
val OnCaffeineBackgroundDark = Color(0xFFEDE0D8)
val CaffeineSurfaceDark = Color(0xFF17120F)
val OnCaffeineSurfaceDark = Color(0xFFEDE0D8)
val CaffeineSurfaceVariantDark = Color(0xFF50453D)
val OnCaffeineSurfaceVariantDark = Color(0xFFD1C5BB)
val CaffeineOutlineDark = Color(0xFF9D8C82)
val CaffeineOutlineVariantDark = Color(0xFF50453D)
val CaffeineSurfaceDimDark = Color(0xFF17120F)
val CaffeineSurfaceBrightDark = Color(0xFF413732)
val CaffeineSurfaceLowestDark = Color(0xFF120D0B)
val CaffeineSurfaceLowDark = Color(0xFF201A17)
val CaffeineSurfaceContainerDark = Color(0xFF241E1A)
val CaffeineSurfaceHighDark = Color(0xFF2F2824)
val CaffeineSurfaceHighestDark = Color(0xFF3A322E)
val CaffeineInverseSurfaceDark = Color(0xFFEDE0D8)
val CaffeineInverseOnSurfaceDark = Color(0xFF352F2B)
val CaffeineInversePrimaryDark = Color(0xFF6D4C2C)

// ── Matcha (green tea) ────────────────────────────────────────────────────────

val MatchaPrimaryLight = Color(0xFF3E6C47)
val OnMatchaPrimaryLight = Color(0xFFFFFFFF)
val MatchaPrimaryContainerLight = Color(0xFFBAEFCA)
val OnMatchaPrimaryContainerLight = Color(0xFF002111)

val MatchaSecondaryLight = Color(0xFF506349)
val OnMatchaSecondaryLight = Color(0xFFFFFFFF)
val MatchaSecondaryContainerLight = Color(0xFFD2E8C8)
val OnMatchaSecondaryContainerLight = Color(0xFF0E1F0A)

val MatchaTertiaryLight = Color(0xFF3A6070)
val OnMatchaTertiaryLight = Color(0xFFFFFFFF)
val MatchaTertiaryContainerLight = Color(0xFFBCE8F8)
val OnMatchaTertiaryContainerLight = Color(0xFF001F28)

val MatchaBackgroundLight = Color(0xFFF5FBF1)
val OnMatchaBackgroundLight = Color(0xFF171D16)
val MatchaSurfaceLight = Color(0xFFF5FBF1)
val OnMatchaSurfaceLight = Color(0xFF171D16)
val MatchaSurfaceVariantLight = Color(0xFFDDE5D9)
val OnMatchaSurfaceVariantLight = Color(0xFF424940)
val MatchaOutlineLight = Color(0xFF72796E)
val MatchaOutlineVariantLight = Color(0xFFC2C9BC)
val MatchaSurfaceDimLight = Color(0xFFD5DCCF)
val MatchaSurfaceBrightLight = Color(0xFFF5FBF1)
val MatchaSurfaceLowestLight = Color(0xFFFFFFFF)
val MatchaSurfaceLowLight = Color(0xFFF0F7EA)
val MatchaSurfaceContainerLight = Color(0xFFEAF2E3)
val MatchaSurfaceHighLight = Color(0xFFE4ECDD)
val MatchaSurfaceHighestLight = Color(0xFFDEE6D7)
val MatchaInverseSurfaceLight = Color(0xFF2C322A)
val MatchaInverseOnSurfaceLight = Color(0xFFEEF5E8)
val MatchaInversePrimaryLight = Color(0xFF9FD2A9)

val MatchaPrimaryDark = Color(0xFF9FD2A9)
val OnMatchaPrimaryDark = Color(0xFF0A3A17)
val MatchaPrimaryContainerDark = Color(0xFF265332)
val OnMatchaPrimaryContainerDark = Color(0xFFBAEFCA)

val MatchaSecondaryDark = Color(0xFFB7CC9E)
val OnMatchaSecondaryDark = Color(0xFF22331E)
val MatchaSecondaryContainerDark = Color(0xFF394B35)
val OnMatchaSecondaryContainerDark = Color(0xFFD2E8C8)

val MatchaTertiaryDark = Color(0xFFA0CCDB)
val OnMatchaTertiaryDark = Color(0xFF023440)
val MatchaTertiaryContainerDark = Color(0xFF1B4856)
val OnMatchaTertiaryContainerDark = Color(0xFFBCE8F8)

val MatchaBackgroundDark = Color(0xFF0F150F)
val OnMatchaBackgroundDark = Color(0xFFDEE5D8)
val MatchaSurfaceDark = Color(0xFF0F150F)
val OnMatchaSurfaceDark = Color(0xFFDEE5D8)
val MatchaSurfaceVariantDark = Color(0xFF424940)
val OnMatchaSurfaceVariantDark = Color(0xFFC2C9BC)
val MatchaOutlineDark = Color(0xFF8C9488)
val MatchaOutlineVariantDark = Color(0xFF424940)
val MatchaSurfaceDimDark = Color(0xFF0F150F)
val MatchaSurfaceBrightDark = Color(0xFF353B33)
val MatchaSurfaceLowestDark = Color(0xFF0A100A)
val MatchaSurfaceLowDark = Color(0xFF181E17)
val MatchaSurfaceContainerDark = Color(0xFF1C231B)
val MatchaSurfaceHighDark = Color(0xFF272E25)
val MatchaSurfaceHighestDark = Color(0xFF323930)
val MatchaInverseSurfaceDark = Color(0xFFDEE5D8)
val MatchaInverseOnSurfaceDark = Color(0xFF2C322A)
val MatchaInversePrimaryDark = Color(0xFF3E6C47)

// ── Ocean (deep blue) ─────────────────────────────────────────────────────────

val OceanPrimaryLight = Color(0xFF00668A)
val OnOceanPrimaryLight = Color(0xFFFFFFFF)
val OceanPrimaryContainerLight = Color(0xFFC5E8FF)
val OnOceanPrimaryContainerLight = Color(0xFF001E2E)

val OceanSecondaryLight = Color(0xFF4C626E)
val OnOceanSecondaryLight = Color(0xFFFFFFFF)
val OceanSecondaryContainerLight = Color(0xFFCFE6F5)
val OnOceanSecondaryContainerLight = Color(0xFF081E27)

val OceanTertiaryLight = Color(0xFF55618F)
val OnOceanTertiaryLight = Color(0xFFFFFFFF)
val OceanTertiaryContainerLight = Color(0xFFDDE1FF)
val OnOceanTertiaryContainerLight = Color(0xFF0F1848)

val OceanBackgroundLight = Color(0xFFF5FAFF)
val OnOceanBackgroundLight = Color(0xFF171C1F)
val OceanSurfaceLight = Color(0xFFF5FAFF)
val OnOceanSurfaceLight = Color(0xFF171C1F)
val OceanSurfaceVariantLight = Color(0xFFD9E3EC)
val OnOceanSurfaceVariantLight = Color(0xFF41494F)
val OceanOutlineLight = Color(0xFF71797F)
val OceanOutlineVariantLight = Color(0xFFBDC7CF)
val OceanSurfaceDimLight = Color(0xFFD4DEE7)
val OceanSurfaceBrightLight = Color(0xFFF5FAFF)
val OceanSurfaceLowestLight = Color(0xFFFFFFFF)
val OceanSurfaceLowLight = Color(0xFFF0F5FA)
val OceanSurfaceContainerLight = Color(0xFFEAF0F5)
val OceanSurfaceHighLight = Color(0xFFE4EAF0)
val OceanSurfaceHighestLight = Color(0xFFDDE5EB)
val OceanInverseSurfaceLight = Color(0xFF2B3134)
val OceanInverseOnSurfaceLight = Color(0xFFECF2F7)
val OceanInversePrimaryLight = Color(0xFF7ECFF5)

val OceanPrimaryDark = Color(0xFF7ECFF5)
val OnOceanPrimaryDark = Color(0xFF00364C)
val OceanPrimaryContainerDark = Color(0xFF004D6B)
val OnOceanPrimaryContainerDark = Color(0xFFC5E8FF)

val OceanSecondaryDark = Color(0xFFB3CAD8)
val OnOceanSecondaryDark = Color(0xFF1E3340)
val OceanSecondaryContainerDark = Color(0xFF344A57)
val OnOceanSecondaryContainerDark = Color(0xFFCFE6F5)

val OceanTertiaryDark = Color(0xFFBAC5FF)
val OnOceanTertiaryDark = Color(0xFF233190)
val OceanTertiaryContainerDark = Color(0xFF3B4B90)
val OnOceanTertiaryContainerDark = Color(0xFFDDE1FF)

val OceanBackgroundDark = Color(0xFF0D1417)
val OnOceanBackgroundDark = Color(0xFFDDE3E8)
val OceanSurfaceDark = Color(0xFF0D1417)
val OnOceanSurfaceDark = Color(0xFFDDE3E8)
val OceanSurfaceVariantDark = Color(0xFF41494F)
val OnOceanSurfaceVariantDark = Color(0xFFBDC7CF)
val OceanOutlineDark = Color(0xFF8A9299)
val OceanOutlineVariantDark = Color(0xFF41494F)
val OceanSurfaceDimDark = Color(0xFF0D1417)
val OceanSurfaceBrightDark = Color(0xFF32383B)
val OceanSurfaceLowestDark = Color(0xFF080F12)
val OceanSurfaceLowDark = Color(0xFF15191C)
val OceanSurfaceContainerDark = Color(0xFF191F22)
val OceanSurfaceHighDark = Color(0xFF23292D)
val OceanSurfaceHighestDark = Color(0xFF2E3437)
val OceanInverseSurfaceDark = Color(0xFFDDE3E8)
val OceanInverseOnSurfaceDark = Color(0xFF2B3134)
val OceanInversePrimaryDark = Color(0xFF00668A)

// ── Sakura (cherry blossom) ───────────────────────────────────────────────────

val SakuraPrimaryLight = Color(0xFF9B2C50)
val OnSakuraPrimaryLight = Color(0xFFFFFFFF)
val SakuraPrimaryContainerLight = Color(0xFFFFD9E4)
val OnSakuraPrimaryContainerLight = Color(0xFF3E001A)

val SakuraSecondaryLight = Color(0xFF755767)
val OnSakuraSecondaryLight = Color(0xFFFFFFFF)
val SakuraSecondaryContainerLight = Color(0xFFFFD8EB)
val OnSakuraSecondaryContainerLight = Color(0xFF2C1524)

val SakuraTertiaryLight = Color(0xFF7B5735)
val OnSakuraTertiaryLight = Color(0xFFFFFFFF)
val SakuraTertiaryContainerLight = Color(0xFFFFDDBD)
val OnSakuraTertiaryContainerLight = Color(0xFF2D1700)

val SakuraBackgroundLight = Color(0xFFFFF8F9)
val OnSakuraBackgroundLight = Color(0xFF22191A)
val SakuraSurfaceLight = Color(0xFFFFF8F9)
val OnSakuraSurfaceLight = Color(0xFF22191A)
val SakuraSurfaceVariantLight = Color(0xFFF1DDE0)
val OnSakuraSurfaceVariantLight = Color(0xFF514346)
val SakuraOutlineLight = Color(0xFF7F7174)
val SakuraOutlineVariantLight = Color(0xFFD5C1C4)
val SakuraSurfaceDimLight = Color(0xFFEDD1D4)
val SakuraSurfaceBrightLight = Color(0xFFFFF8F9)
val SakuraSurfaceLowestLight = Color(0xFFFFFFFF)
val SakuraSurfaceLowLight = Color(0xFFFCF2F3)
val SakuraSurfaceContainerLight = Color(0xFFF6EBEC)
val SakuraSurfaceHighLight = Color(0xFFF0E3E4)
val SakuraSurfaceHighestLight = Color(0xFFEADBDC)
val SakuraInverseSurfaceLight = Color(0xFF382E2F)
val SakuraInverseOnSurfaceLight = Color(0xFFFFEDF0)
val SakuraInversePrimaryLight = Color(0xFFFFB2CA)

val SakuraPrimaryDark = Color(0xFFFFB2CA)
val OnSakuraPrimaryDark = Color(0xFF5E0028)
val SakuraPrimaryContainerDark = Color(0xFF7D1040)
val OnSakuraPrimaryContainerDark = Color(0xFFFFD9E4)

val SakuraSecondaryDark = Color(0xFFE5BECF)
val OnSakuraSecondaryDark = Color(0xFF432939)
val SakuraSecondaryContainerDark = Color(0xFF5C3F4F)
val OnSakuraSecondaryContainerDark = Color(0xFFFFD8EB)

val SakuraTertiaryDark = Color(0xFFEFC191)
val OnSakuraTertiaryDark = Color(0xFF452C0A)
val SakuraTertiaryContainerDark = Color(0xFF5F411E)
val OnSakuraTertiaryContainerDark = Color(0xFFFFDDBD)

val SakuraBackgroundDark = Color(0xFF181011)
val OnSakuraBackgroundDark = Color(0xFFEDE0DE)
val SakuraSurfaceDark = Color(0xFF181011)
val OnSakuraSurfaceDark = Color(0xFFEDE0DE)
val SakuraSurfaceVariantDark = Color(0xFF514346)
val OnSakuraSurfaceVariantDark = Color(0xFFD5C1C4)
val SakuraOutlineDark = Color(0xFF9D8A8D)
val SakuraOutlineVariantDark = Color(0xFF514346)
val SakuraSurfaceDimDark = Color(0xFF181011)
val SakuraSurfaceBrightDark = Color(0xFF413435)
val SakuraSurfaceLowestDark = Color(0xFF120B0B)
val SakuraSurfaceLowDark = Color(0xFF21181A)
val SakuraSurfaceContainerDark = Color(0xFF261C1E)
val SakuraSurfaceHighDark = Color(0xFF312629)
val SakuraSurfaceHighestDark = Color(0xFF3C3033)
val SakuraInverseSurfaceDark = Color(0xFFEDE0DE)
val SakuraInverseOnSurfaceDark = Color(0xFF382E2F)
val SakuraInversePrimaryDark = Color(0xFF9B2C50)
